"""Build formatted Excel workbooks from selected export data."""
from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill


HEADER_FILL = PatternFill("solid", fgColor="1E3A8A")
TITLE_FONT = Font(name="Times New Roman", bold=True, size=12)
HEADER_FONT = Font(name="Times New Roman", color="FFFFFF", bold=True, size=12)


def _write_section(ws, start_row, title, headers, rows, left_cols=()):
    ws.cell(row=start_row, column=1, value=title).font = TITLE_FONT
    start_row += 1

    for col, header in enumerate(headers, start=1):
        cell = ws.cell(row=start_row, column=col, value=header)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="left" if col in left_cols else "center")

    for offset, row in enumerate(rows, start=1):
        for col, value in enumerate(row, start=1):
            cell = ws.cell(row=start_row + offset, column=col, value=value)
            cell.alignment = Alignment(horizontal="left" if col in left_cols else "center")

    return start_row + len(rows) + 2


def build_export_workbook(report_title, report_ref, selections):
    """Return an in-memory .xlsx file from export selection payload."""
    wb = Workbook()
    ws = wb.active
    ws.title = "GIS INFO"
    ws["A1"] = report_title or "EKSESAIS"
    ws["A1"].font = Font(name="Times New Roman", bold=True, size=12, color="000000")
    ws["A2"] = f"Reference: {report_ref or '—'}"
    ws["A2"].font = Font(name="Times New Roman", size=12)
    ws["A3"] = "Generated by GIS INFO"
    ws["A3"].font = Font(name="Times New Roman", size=12)

    row = 5
    topo = selections.get("topography") or []
    sjungu = selections.get("sjungu") or []
    if topo or sjungu:
        combined = [
            ["Topo Raster", r.get("sheetNum"), r.get("sheetName"), r.get("sheetScale"), r.get("release_year", "")]
            for r in topo
        ] + [
            ["Topo", r.get("sheetNum"), r.get("sheetName"), r.get("sheetScale"), ""]
            for r in sjungu
        ]
        row = _write_section(
            ws,
            row,
            "TOPO RASTER & TOPO",
            ["Type", "Sheet Number", "Sheet Name", "Scale", "Year"],
            combined,
        )

    land = selections.get("landused") or []
    if land:
        row = _write_section(
            ws,
            row,
            "LANDUSED",
            ["No.", "Category", "Landused ID"],
            [[idx + 1, r.get("category"), idx + 1] for idx, r in enumerate(land)],
            left_cols=(2,),
        )

    dted = selections.get("dted") or []
    if dted:
        _write_section(
            ws,
            row,
            "DTED",
            ["No.", "ID / Path", "Level"],
            [[idx + 1, r.get("id_name"), r.get("level")] for idx, r in enumerate(dted)],
            left_cols=(2,),
        )

    for column in ws.columns:
        max_length = 0
        column_letter = column[0].column_letter
        for cell in column:
            if cell.value is not None:
                max_length = max(max_length, len(str(cell.value)))
        ws.column_dimensions[column_letter].width = min(max_length + 2, 50)

    buffer = BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer
